export const shotStyles: string[] = [
  "Medium Shot",
  "Full-Body Shot",
  "Close-up Portrait",
  "Cowboy Shot (Mid-thigh up)",
  "Wide Shot (Shows context)",
  "Extreme Wide Shot",
  "Low-Angle (Looking up)",
  "High-Angle (Looking down)",
  "Dutch Angle (Tilted)",
  "Eye-Level Shot",
  "Profile Shot (Side view)",
  "Over-the-Shoulder Shot",
  "Point-of-View (POV)",
  "Worm's-Eye View (From ground)",
  "Bird's-Eye View (Directly above)",
  "Dramatic Silhouette",
  "Fashion Magazine Cover Style",
  "Candid Street Photography",
  "Cinematic Frame",
  "Glamour Shot",
  "Intimate Handheld Shot",
  "Documentary Style",
  "Noir Film Style",
  "Found Footage Style",
  "Time-lapse Style",
  "Slow Motion Effect",
  "Split Diopter Shot",
  "Vertigo Effect (Dolly Zoom)",
  "Lens Whacking Style",
  "Minimalist Composition"
];

export const lightStyles: string[] = [
  "Soft Studio Light",
  "Golden Hour Sunlight",
  "Dramatic Rembrandt Lighting",
  "Neon City Lights at Night",
  "Cinematic Moody Lighting",
  "High-Key Bright Lighting",
  "Low-Key Dark & Shadowy",
  "Backlit with Lens Flare",
  "Hard Direct Midday Sun",
  "Split Lighting (Half light, half shadow)",
  "Butterfly Lighting (High key)",
  "Loop Lighting (Portrait style)",
  "Rim Lighting (Outlines the subject)",
  "Chiaroscuro (Strong contrast)",
  "Natural Ambient Daylight",
  "Cozy Candlelight",
  "Warm Firelight",
  "Underwater Caustics",
  "Projector Light Patterns",
  "Mystical Moonlight",
  "Volumetric Light Rays",
  "Gobo Patterns (Shadow patterns)",
  "Fairy Lights (Bokeh)",
  "Bioluminescent Glow",
  "Cyberpunk Neon Haze",
  "Haunted House Eerie Light",
  "Sunrise/Sunset Hues",
  "Monochromatic Light",
  "Disco Ball Reflections",
  "Projected Galaxy Light"
];

export const aspectRatios: string[] = [
  "Original",
  "1:1 (Square)",
  "4:5 (Portrait)",
  "9:16 (Story)",
  "3:4 (Classic Portrait)",
  "16:9 (Widescreen)",
  "4:3 (Classic Landscape)",
];