export const hairTemplatesID = {
  wanita: [
    "Rambut Panjang Bergelombang",
    "Bob Sebahu Klasik",
    "Cepol Atas Berantakan (Messy Bun)",
    "Sanggul Chignon Elegan",
    "Potongan Pixie Pendek",
    "Ikal Hollywood Bervolume",
    "Rambut Lurus dengan Poni Rata",
    "Mahkota Kepang Bohemian",
    "Setengah Ikat dengan Ikal Lepas",
    "Ombak Gaya Hollywood Jadul",
    "Potongan Shag Berlapis",
    "Bob Asimetris",
    "Kepang Ekor Ikan (Fishtail Braid)",
    "Kepang Belanda (Dutch Braids)",
    "Rambut Panjang dengan Layer Bulu",
    "Afro Keriting",
    "Lob (Long Bob) Potongan Rata",
    "Gaya Vintage Victory Rolls",
    "Cepol Luar Angkasa (Space Buns)",
    "Kepang Air Terjun (Waterfall Braid)",
    "Rambut Lurus Licin (Glass Hair)",
    "Bob Pendek dengan Poni Mikro",
    "Kuncir Kuda Gelembung (Bubble Ponytail)",
    "Gaya Retro Beehive",
    "Kepang Mohawk",
    "Gaya Keriting Papan (Crimped Hair)",
    "Ikal Kecil Padat",
    "Sanggul Perancis (French Twist)",
    "Poni Tirai dengan Layer Panjang",
    "Potongan Buzz Cut Wanita",
    "Mullet Modern Wanita",
    "Rambut Ikal Alami Sebahu",
    "Gaya Rambut Basah (Wet Look)",
    "Potongan Bowl Cut Modern",
    "Kuncir Kuda Tinggi Ramping",
    "Rambut Super Panjang Lurus",
    "Warna Rambut Pastel",
    "Highlight Balayage Halus",
    "Rambut Ombre Dramatis",
    "Aksen Kepang Kecil",
    "Gaya Rambut Pin-up",
    "Ikal Spiral (Corkscrew Curls)",
    "Rambut Disisir ke Belakang (Slicked Back)",
    "Kepang Halo",
    "Potongan Undercut Wanita",
    "Potongan Bob Tumpul",
    "Rambut Keriting Kribo",
    "Gaya Rambut Kepang Jagung (Cornrows)",
    "Potongan Rambut Serigala (Wolf Cut)",
    "Rambut Keriting dengan Poni",
  ],
  pria: [
    "Belah Samping Klasik",
    "Quiff Bertekstur dengan Sisi Pudar",
    "Undercut Disisir ke Belakang",
    "Potongan Crew Cut Pendek dan Rapi",
    "Gaya Bro Flow Panjang Sedang",
    "Potongan Militer High and Tight",
    "Cepol Pria (Man Bun) dengan Jenggot",
    "Pompadour dengan Sentuhan Modern",
    "Rambut Keriting dengan Taper Fade",
    "Rambut Bertekstur Spiky",
    "Potongan Buzz Cut",
    "Potongan Rambut Ivy League",
    "Potongan Caesar",
    "French Crop dengan Poni",
    "Rambut Gondrong Gaya Peselancar",
    "Faux Hawk",
    "Comb Over dengan Garis Belahan Tegas",
    "Rambut Gimbal (Dreadlocks)",
    "Poni Siku (Angular Fringe)",
    "Afro Pendek dengan Garis Tepi",
    "Wavy Crop Top Fade",
    "Gaya Rambut Disisir ke Atas",
    "Sisi Pendek dengan Atas Panjang",
    "Gaya Executive Contour",
    "Undercut Terputus (Disconnected Undercut)",
    "Potongan Taper dengan Ikal Alami",
    "Mullet Modern",
    "Poni Berantakan (Messy Fringe)",
    "Kepang Jagung (Cornrows)",
    "Rambut Disisir ke Belakang dengan Low Fade",
    "Potongan Two Block",
    "Gaya Comma Hair",
    "Rambut Ikal Panjang Terurai",
    "Potongan Rambut Edgar",
    "Slick Back Wet Look",
    "Potongan Rambut Flat Top",
    "Hard Part dengan Pompadour",
    "Potongan Induction Cut (Sangat Pendek)",
    "Gaya Rambut Top Knot Pria",
    "Side Part dengan Volume",
    "Rambut Keriting Pendek Berantakan",
    "Fringe Up",
    "Potongan Rambut Belah Tengah",
    "Gaya Rambut Bergelombang Alami",
    "Taper Fade dengan Rambut Bertekstur",
    "Potongan Quiff Panjang",
    "High Top Fade",
    "Rambut Mohawk Tipis",
    "Gaya rambut disisir jari",
    "Gaya rambut line up",
  ]
};
