export const hairTemplates = {
  female: [
    "Sleek High Ponytail",
    "Long, Wavy Beach Hair",
    "Classic Shoulder-Length Bob",
    "Messy Top Knot Bun",
    "Elegant Chignon Updo",
    "Short and Sassy Pixie Cut",
    "Voluminous Hollywood Curls",
    "Straight, Silky Hair with Blunt Bangs",
    "Bohemian Braided Crown",
    "Half-Up, Half-Down with Loose Curls",
    "Side-Swept Old Hollywood Waves",
    "Layered Shag Cut",
    "Asymmetrical Bob",
    "Fishtail Braid",
    "Dutch Braids",
    "Long Hair with Feathered Layers",
    "Curly Afro",
    "Blunt Cut Lob (Long Bob)",
    "Vintage Victory Rolls",
    "Space Buns",
    "Waterfall Braid",
    "Pin-Straight Glass Hair",
    "Short Bob with Micro Bangs",
    "Bubble Ponytail",
    "Retro Beehive",
    "Mohawk Braid",
    "Crimped 90s Style",
    "Tightly Coiled Ringlets",
    "French Twist",
    "Curtain Bangs with Long Layers"
  ],
  male: [
    "Classic Side Part",
    "Textured Quiff with Faded Sides",
    "Slicked Back Undercut",
    "Short and Sharp Crew Cut",
    "Medium-Length Bro Flow",
    "High and Tight Military Cut",
    "Man Bun with Beard",
    "Pompadour with a Modern Twist",
    "Curly Hair with a Taper Fade",
    "Spiky Textured Hair",
    "Buzz Cut",
    "Ivy League Haircut",
    "Caesar Cut",
    "French Crop with a Fringe",
    "Long Surfer Hair",
    "Faux Hawk",
    "Hard Part Comb Over",
    "Dreadlocks",
    "Angular Fringe",
    "Short Afro with a Line Up",
    "Wavy Crop Top Fade",
    "Brushed Up Hairstyle",
    "Short Sides with a Long Top",
    "The Executive Contour",
    "Disconnected Undercut",
    "Tapered Haircut with Natural Curls",
    "Modern Mullet",
    "Messy Fringe",
    "Cornrows",
    "Slicked Back with a Low Fade"
  ]
};

export const expressionTemplates = [
  "Same as uploaded photo",
  "Natural Smile",
  "Serious",
  "Joyful Laugh",
  "Confident Smirk",
  "Thoughtful",
  "Surprised",
  "Playful Wink",
  "Determined",
  "Serene",
  "Slight Frown"
];